# Generated by Django 6.0.4 on 2026-04-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='contact_number',
            field=models.CharField(default=9398965934, max_length=15),
            preserve_default=False,
        ),
    ]
